[package]
name = "tomllib"
version = "0.1.0"
authors = ["Joel Self <joel@dislocal.com>"]

[dependencies.nom]
git = "https://github.com/Geal/nom.git"

features = ["regexp_macros"]
[dependencies.regex]
[dependencies.regex_macros]

[[bin]]
name = "tomlkit"