[package]
name = "tomllib"
version = "0.1.0"
authors = ["Joel Self <self@jself.com>"]
description = "A format-preserving TOML file parser and manipulator"
license = "MIT"
repository = "https://github.com/joelself/tomllib"
readme = "README.md"
#documentation = "http://rust.unhandledexpression.com/tomllib/"
keywords = ["toml", "parser", "encode", "decode", "nom"]

[dependencies.nom]
version = "^1.2.0"
features = ["regexp"]

[dependencies.regex]
version = "^0.1.48"

# Uncomment these, and comment out the regexp feature to turn on statically compiled regexes
#features = ["regexp_macros"]
#[dependencies.regex_macros]
[dependencies.log]
version = "^0.3.5"
[dependencies.env_logger]
version = "^0.3.2"

[[bin]]
name = "tomlkit"

